{% set name = "wapordl" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wapordl-{{ version }}.tar.gz
  sha256: 627fc01db6d96e6a0c2870f9285ddaed3ea138d2e8ca704af3fd0953b60e3622

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - tqdm
    - pandas >=2.1.0
    - numpy
    - gdal >=3.4.0
    - shapely >=2.0.0

test:
  imports:
    - wapordl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/cioapps/wapordl
  summary: Easily download subsets of WaPOR3 data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bertcoerver
