{% set name = "wapordl" %}
{% set version = "1.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wapordl-{{ version }}.tar.gz
  sha256: 4093834f105abda09b677e9d0f5ce55a2eb1a4f68ce890cb2829ac6cbea2fb78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - tqdm
    - pandas >=2.1.0,<3
    - numpy >=1.15,<3
    - gdal >=3.4.0,<4
    - xarray
    - rioxarray
    - dask
    - libgdal-netcdf
    - matplotlib-base

test:
  imports:
    - wapordl
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://bitbucket.org/cioapps/wapordl
  summary: Easily download subsets of WaPOR3 data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bertcoerver
