{% set name = "wapordl" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wapordl-{{ version }}.tar.gz
  sha256: 6b09593e71be454a5eb2246f9a63b48c6fe089e6bc0ea8b6b88dad0f8c6d42b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - pandas >=2.1.0
    - numpy
    - gdal >=3.4.0

test:
  imports:
    - wapordl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bertcoerver/wapordl
  summary: Easily download subsets of WaPOR3 data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bertcoerver
