{% set name = "wapordl" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wapordl-{{ version }}.tar.gz
  sha256: 623382a72baf6710bc61281a1122edf894e4f67823d893fa4f37fe47ec938f35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - tqdm
    - pandas >=2.1.0
    - numpy
    - gdal >=3.4.0
    - shapely >=2.0.0

test:
  imports:
    - wapordl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/cioapps/wapordl
  summary: Easily download subsets of WaPOR3 data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bertcoerver
